services:
  - type: web
    name: muzlib
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --worker-class uvicorn.workers.UvicornWorker
    envVars:
      - key: DATABASE_URL
        sync: false
